name: Install and Configure Hadoop

on: [push]

jobs:
  install-hadoop:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Download and Install Hadoop
      run: |
        wget https://downloads.apache.org/hadoop/common/hadoop-3.3.0/hadoop-3.3.0.tar.gz
        tar -xzf hadoop-3.3.0.tar.gz
        sudo mv hadoop-3.3.0 /opt/hadoop
        echo 'export HADOOP_HOME=/opt/hadoop' >> $GITHUB_ENV
        echo 'export PATH=$PATH:$HADOOP_HOME/bin:$HADOOP_HOME/sbin' >> $GITHUB_ENV

    - name: Configure Hadoop
      run: |
        # Add your Hadoop configuration here
        # For example, you can update core-site.xml, hdfs-site.xml, etc.

    - name: Verify Hadoop Installation
      run: hadoop version
